version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: netops-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: netops_db
      POSTGRES_USER: netops_user
      POSTGRES_PASSWORD: netops_pass
      # Optional: Performance tuning
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=en_US.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d  # Optional: init scripts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U netops_user -d netops_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - netops-network

  # Redis (for future caching/Celery)
  redis:
    image: redis:7-alpine
    container_name: netops-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - netops-network

  # pgAdmin (Optional: Web-based PostgreSQL management)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: netops-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@netops.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - netops-network
    profiles:
      - tools  # Only start with --profile tools

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  netops-network:
    driver: bridge
